"""create CRM schema

Revision ID: 0001
Revises:
Create Date: 2026-09-22 19:26:11.617487

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mainsequence_crm__workspace",
        sa.Column("uid", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("default_currency", sa.CHAR(length=3), nullable=False),
        sa.Column("timezone", sa.String(length=100), nullable=False),
        sa.Column("configuration", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("configuration_version", sa.BigInteger(), nullable=False),
        sa.Column("mutation_epoch", sa.BigInteger(), nullable=False),
        sa.Column("export_fence_job_uid", sa.Uuid(), nullable=True),
        sa.Column("export_fence_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "default_currency ~ '^[A-Z]{3}$'", name="ck_mainsequence_crm__workspace_1"
        ),
        sa.CheckConstraint(
            "(export_fence_job_uid IS NULL) = (export_fence_expires_at IS NULL)",
            name="ck_mainsequence_crm__workspace_4",
        ),
        sa.CheckConstraint("configuration_version > 0", name="ck_mainsequence_crm__workspace_3"),
        sa.CheckConstraint("mutation_epoch >= 0", name="ck_mainsequence_crm__workspace_2"),
        sa.PrimaryKeyConstraint("uid"),
    )
    op.create_table(
        "mainsequence_crm__activity_event",
        sa.Column("uid", sa.Uuid(), nullable=False),
        sa.Column("workspace_uid", sa.Uuid(), nullable=False),
        sa.Column("entity_type", sa.String(length=30), nullable=False),
        sa.Column("entity_uid", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=100), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor_uid", sa.Uuid(), nullable=True),
        sa.Column("origin", sa.String(length=20), nullable=False),
        sa.Column("command_uid", sa.Uuid(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("changes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source_attribution", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint(
            "origin IN ('live','import','system')", name="ck_mainsequence_crm__activity_event_1"
        ),
        sa.ForeignKeyConstraint(
            ["workspace_uid"],
            ["mainsequence_crm__workspace.uid"],
            name="fk_mainsequence_crm__activity_event_workspace_uid",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("uid"),
        sa.UniqueConstraint(
            "workspace_uid",
            "command_uid",
            "entity_type",
            "entity_uid",
            "kind",
            name="uq_mainsequence_crm__activity_event_workspace_uid_command_uid_e",
        ),
        sa.UniqueConstraint(
            "workspace_uid", "uid", name="uq_mainsequence_crm__activity_event_workspace_uid_uid"
        ),
    )
    op.create_index(
        "ix_mainsequence_crm__activity_event_1",
        "mainsequence_crm__activity_event",
        ["workspace_uid", "occurred_at", "uid"],
        unique=False,
    )
    op.create_index(
        "ix_mainsequence_crm__activity_event_2",
        "mainsequence_crm__activity_event",
        ["workspace_uid", "entity_type", "entity_uid", "occurred_at", "uid"],
        unique=False,
    )
    op.create_table(
        "mainsequence_crm__command_receipt",
        sa.Column("uid", sa.Uuid(), nullable=False),
        sa.Column("workspace_uid", sa.Uuid(), nullable=False),
        sa.Column("actor_uid", sa.Uuid(), nullable=False),
        sa.Column("operation_key", sa.String(length=255), nullable=False),
        sa.Column("key_hash", sa.CHAR(length=64), nullable=False),
        sa.Column("request_hash", sa.CHAR(length=64), nullable=False),
        sa.Column("http_status", sa.SmallInteger(), nullable=False),
        sa.Column("response_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "http_status >= 200 AND http_status < 300",
            name="ck_mainsequence_crm__command_receipt_1",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_uid"],
            ["mainsequence_crm__workspace.uid"],
            name="fk_mainsequence_crm__command_receipt_workspace_uid",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("uid"),
        sa.UniqueConstraint(
            "workspace_uid",
            "actor_uid",
            "operation_key",
            "key_hash",
            name="uq_mainsequence_crm__command_receipt_workspace_uid_actor_uid_op",
        ),
        sa.UniqueConstraint(
            "workspace_uid", "uid", name="uq_mainsequence_crm__command_receipt_workspace_uid_uid"
        ),
    )
    op.create_index(
        "ix_mainsequence_crm__command_receipt_1",
        "mainsequence_crm__command_receipt",
        ["expires_at"],
        unique=False,
    )
    op.create_table(
        "mainsequence_crm__company",
        sa.Column("uid", sa.Uuid(), nullable=False),
        sa.Column("workspace_uid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_uid", sa.Uuid(), nullable=True),
        sa.Column("updated_by_uid", sa.Uuid(), nullable=True),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("owner_uid", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("sector_key", sa.String(length=100), nullable=True),
        sa.Column("size_category", sa.SmallInteger(), nullable=True),
        sa.Column("linkedin_url", sa.Text(), nullable=True),
        sa.Column("website", sa.Text(), nullable=True),
        sa.Column("normalized_domain", sa.String(length=255), nullable=True),
        sa.Column("phone_number", sa.String(length=100), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("zipcode", sa.String(length=40), nullable=True),
        sa.Column("city", sa.String(length=255), nullable=True),
        sa.Column("state_abbr", sa.String(length=100), nullable=True),
        sa.Column("country", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("revenue_text", sa.Text(), nullable=True),
        sa.Column("tax_identifier", sa.String(length=255), nullable=True),
        sa.Column("context_links", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("logo_ref", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("source_created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("length(trim(name)) > 0", name="ck_mainsequence_crm__company_1"),
        sa.CheckConstraint(
            "size_category IS NULL OR size_category IN (1,10,50,250,500)",
            name="ck_mainsequence_crm__company_2",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_uid"],
            ["mainsequence_crm__workspace.uid"],
            name="fk_mainsequence_crm__company_workspace_uid",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("uid"),
        sa.UniqueConstraint(
            "workspace_uid", "uid", name="uq_mainsequence_crm__company_workspace_uid_uid"
        ),
    )
    op.create_index(
        "ix_mainsequence_crm__company_1",
        "mainsequence_crm__company",
        ["workspace_uid", "archived_at", "name", "uid"],
        unique=False,
    )
    op.create_index(
        "ix_mainsequence_crm__company_2",
        "mainsequence_crm__company",
        ["workspace_uid", "owner_uid"],
        unique=False,
    )
    op.create_index(
        "ix_mainsequence_crm__company_3",
        "mainsequence_crm__company",
        ["workspace_uid", "normalized_domain"],
        unique=False,
    )
    op.create_table(
        "mainsequence_crm__entity_redirect",
        sa.Column("uid", sa.Uuid(), nullable=False),
        sa.Column("workspace_uid", sa.Uuid(), nullable=False),
        sa.Column("entity_type", sa.String(length=30), nullable=False),
        sa.Column("from_uid", sa.Uuid(), nullable=False),
        sa.Column("to_uid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("command_uid", sa.Uuid(), nullable=False),
        sa.CheckConstraint("from_uid <> to_uid", name="ck_mainsequence_crm__entity_redirect_1"),
        sa.ForeignKeyConstraint(
            ["workspace_uid"],
            ["mainsequence_crm__workspace.uid"],
            name="fk_mainsequence_crm__entity_redirect_workspace_uid",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("uid"),
        sa.UniqueConstraint(
            "workspace_uid",
            "entity_type",
            "from_uid",
            name="uq_mainsequence_crm__entity_redirect_workspace_uid_entity_type_",
        ),
        sa.UniqueConstraint(
            "workspace_uid", "uid", name="uq_mainsequence_crm__entity_redirect_workspace_uid_uid"
        ),
    )
    op.create_index(
        "ix_mainsequence_crm__entity_redirect_1",
        "mainsequence_crm__entity_redirect",
        ["workspace_uid", "entity_type", "to_uid"],
        unique=False,
    )
    op.create_table(
        "mainsequence_crm__pipeline",
        sa.Column("uid", sa.Uuid(), nullable=False),
        sa.Column("workspace_uid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_uid", sa.Uuid(), nullable=True),
        sa.Column("updated_by_uid", sa.Uuid(), nullable=True),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("board_version", sa.BigInteger(), nullable=False),
        sa.CheckConstraint("board_version > 0", name="ck_mainsequence_crm__pipeline_1"),
        sa.CheckConstraint("version > 0", name="ck_mainsequence_crm__pipeline_2"),
        sa.ForeignKeyConstraint(
            ["workspace_uid"],
            ["mainsequence_crm__workspace.uid"],
            name="fk_mainsequence_crm__pipeline_workspace_uid",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("uid"),
        sa.UniqueConstraint(
            "workspace_uid", "uid", name="uq_mainsequence_crm__pipeline_workspace_uid_uid"
        ),
    )
    op.create_index(
        "ix_mainsequence_crm__pipeline_default",
        "mainsequence_crm__pipeline",
        ["workspace_uid"],
        unique=True,
        postgresql_where=sa.text("is_default = true"),
    )
    op.create_table(
        "mainsequence_crm__source_connection",
        sa.Column("uid", sa.Uuid(), nullable=False),
        sa.Column("workspace_uid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_uid", sa.Uuid(), nullable=True),
        sa.Column("updated_by_uid", sa.Uuid(), nullable=True),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("adapter_id", sa.String(length=100), nullable=False),
        sa.Column("source_account_key", sa.String(length=255), nullable=False),
        sa.Column("configuration", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_uid"],
            ["mainsequence_crm__workspace.uid"],
            name="fk_mainsequence_crm__source_connection_workspace_uid",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("uid"),
        sa.UniqueConstraint(
            "workspace_uid",
            "adapter_id",
            "source_account_key",
            name="uq_mainsequence_crm__source_connection_workspace_uid_adapter_id",
        ),
        sa.UniqueConstraint(
            "workspace_uid", "uid", name="uq_mainsequence_crm__source_connection_workspace_uid_uid"
        ),
    )
    op.create_table(
        "mainsequence_crm__tag",
        sa.Column("uid", sa.Uuid(), nullable=False),
        sa.Column("workspace_uid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_uid", sa.Uuid(), nullable=True),
        sa.Column("updated_by_uid", sa.Uuid(), nullable=True),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("normalized_name", sa.String(length=100), nullable=False),
        sa.Column("tone", sa.String(length=20), nullable=False),
        sa.Column("legacy_color", sa.String(length=100), nullable=True),
        sa.CheckConstraint("length(trim(name)) > 0", name="ck_mainsequence_crm__tag_1"),
        sa.ForeignKeyConstraint(
            ["workspace_uid"],
            ["mainsequence_crm__workspace.uid"],
            name="fk_mainsequence_crm__tag_workspace_uid",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("uid"),
        sa.UniqueConstraint(
            "workspace_uid",
            "normalized_name",
            name="uq_mainsequence_crm__tag_workspace_uid_normalized_name",
        ),
        sa.UniqueConstraint(
            "workspace_uid", "uid", name="uq_mainsequence_crm__tag_workspace_uid_uid"
        ),
    )
    op.create_table(
        "mainsequence_crm__contact",
        sa.Column("uid", sa.Uuid(), nullable=False),
        sa.Column("workspace_uid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_uid", sa.Uuid(), nullable=True),
        sa.Column("updated_by_uid", sa.Uuid(), nullable=True),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("owner_uid", sa.Uuid(), nullable=True),
        sa.Column("company_uid", sa.Uuid(), nullable=True),
        sa.Column("first_name", sa.String(length=255), nullable=True),
        sa.Column("last_name", sa.String(length=255), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("gender", sa.String(length=100), nullable=True),
        sa.Column("background", sa.Text(), nullable=True),
        sa.Column("avatar_ref", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("linkedin_url", sa.Text(), nullable=True),
        sa.Column("emails", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("phones", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=True),
        sa.Column("has_newsletter", sa.Boolean(), nullable=True),
        sa.Column("status_key", sa.String(length=100), nullable=True),
        sa.Column("source_created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("jsonb_typeof(emails) = 'array'", name="ck_mainsequence_crm__contact_2"),
        sa.CheckConstraint("jsonb_typeof(phones) = 'array'", name="ck_mainsequence_crm__contact_3"),
        sa.CheckConstraint(
            "nullif(trim(coalesce(first_name,'')), '') IS NOT NULL OR nullif(trim(coalesce(last_name,'')), '') IS NOT NULL OR jsonb_array_length(emails) > 0",
            name="ck_mainsequence_crm__contact_4",
        ),
        sa.CheckConstraint("version > 0", name="ck_mainsequence_crm__contact_1"),
        sa.ForeignKeyConstraint(
            ["workspace_uid", "company_uid"],
            ["mainsequence_crm__company.workspace_uid", "mainsequence_crm__company.uid"],
            name="fk_mainsequence_crm__contact_workspace_uid_company_uid",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_uid"],
            ["mainsequence_crm__workspace.uid"],
            name="fk_mainsequence_crm__contact_workspace_uid",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("uid"),
        sa.UniqueConstraint(
            "workspace_uid", "uid", name="uq_mainsequence_crm__contact_workspace_uid_uid"
        ),
    )
    op.create_index(
        "ix_mainsequence_crm__contact_1",
        "mainsequence_crm__contact",
        ["workspace_uid", "archived_at", "last_seen", "uid"],
        unique=False,
    )
    op.create_index(
        "ix_mainsequence_crm__contact_2",
        "mainsequence_crm__contact",
        ["workspace_uid", "company_uid"],
        unique=False,
    )
    op.create_index(
        "ix_mainsequence_crm__contact_3",
        "mainsequence_crm__contact",
        ["workspace_uid", "owner_uid"],
        unique=False,
    )
    op.create_table(
        "mainsequence_crm__source_identity",
        sa.Column("uid", sa.Uuid(), nullable=False),
        sa.Column("workspace_uid", sa.Uuid(), nullable=False),
        sa.Column("source_connection_uid", sa.Uuid(), nullable=False),
        sa.Column("entity_type", sa.String(length=30), nullable=False),
        sa.Column("external_id", sa.Text(), nullable=False),
        sa.Column("target_uid", sa.Uuid(), nullable=False),
        sa.Column("source_payload_hash", sa.CHAR(length=64), nullable=False),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_imported_target_version", sa.BigInteger(), nullable=True),
        sa.Column("last_import_job_uid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_uid", "source_connection_uid"],
            [
                "mainsequence_crm__source_connection.workspace_uid",
                "mainsequence_crm__source_connection.uid",
            ],
            name="fk_mainsequence_crm__source_identity_workspace_uid_source_conne",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_uid"],
            ["mainsequence_crm__workspace.uid"],
            name="fk_mainsequence_crm__source_identity_workspace_uid",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("uid"),
        sa.UniqueConstraint(
            "workspace_uid",
            "source_connection_uid",
            "entity_type",
            "external_id",
            name="uq_mainsequence_crm__source_identity_workspace_uid_source_conne",
        ),
        sa.UniqueConstraint(
            "workspace_uid", "uid", name="uq_mainsequence_crm__source_identity_workspace_uid_uid"
        ),
    )
    op.create_index(
        "ix_mainsequence_crm__source_identity_1",
        "mainsequence_crm__source_identity",
        ["workspace_uid", "entity_type", "target_uid"],
        unique=False,
    )
    op.create_table(
        "mainsequence_crm__stage",
        sa.Column("uid", sa.Uuid(), nullable=False),
        sa.Column("workspace_uid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_uid", sa.Uuid(), nullable=True),
        sa.Column("updated_by_uid", sa.Uuid(), nullable=True),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("pipeline_uid", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("outcome", sa.String(length=10), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.CheckConstraint("outcome IN ('open','won','lost')", name="ck_mainsequence_crm__stage_1"),
        sa.CheckConstraint("position >= 0", name="ck_mainsequence_crm__stage_2"),
        sa.ForeignKeyConstraint(
            ["workspace_uid", "pipeline_uid"],
            ["mainsequence_crm__pipeline.workspace_uid", "mainsequence_crm__pipeline.uid"],
            name="fk_mainsequence_crm__stage_workspace_uid_pipeline_uid",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_uid"],
            ["mainsequence_crm__workspace.uid"],
            name="fk_mainsequence_crm__stage_workspace_uid",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("uid"),
        sa.UniqueConstraint(
            "workspace_uid",
            "pipeline_uid",
            "key",
            name="uq_mainsequence_crm__stage_workspace_uid_pipeline_uid_key",
        ),
        sa.UniqueConstraint(
            "workspace_uid",
            "pipeline_uid",
            "uid",
            name="uq_mainsequence_crm__stage_workspace_uid_pipeline_uid_uid",
        ),
        sa.UniqueConstraint(
            "workspace_uid", "uid", name="uq_mainsequence_crm__stage_workspace_uid_uid"
        ),
    )
    op.create_index(
        "ix_mainsequence_crm__stage_1",
        "mainsequence_crm__stage",
        ["workspace_uid", "pipeline_uid", "position", "uid"],
        unique=False,
    )
    op.create_table(
        "mainsequence_crm__transfer_job",
        sa.Column("uid", sa.Uuid(), nullable=False),
        sa.Column("workspace_uid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_uid", sa.Uuid(), nullable=True),
        sa.Column("updated_by_uid", sa.Uuid(), nullable=True),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("direction", sa.String(length=10), nullable=False),
        sa.Column("adapter_id", sa.String(length=100), nullable=False),
        sa.Column("source_connection_uid", sa.Uuid(), nullable=True),
        sa.Column("initiator_uid", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("input_manifest", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("mapping", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("mapping_revision", sa.Integer(), nullable=False),
        sa.Column("plan_hash", sa.CHAR(length=64), nullable=True),
        sa.Column("validation_report", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("cancel_requested", sa.Boolean(), nullable=False),
        sa.Column("lease_holder", sa.String(length=255), nullable=True),
        sa.Column("lease_epoch", sa.BigInteger(), nullable=False),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_summary", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("output_manifest", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint(
            "direction IN ('import','export')", name="ck_mainsequence_crm__transfer_job_1"
        ),
        sa.ForeignKeyConstraint(
            ["workspace_uid", "source_connection_uid"],
            [
                "mainsequence_crm__source_connection.workspace_uid",
                "mainsequence_crm__source_connection.uid",
            ],
            name="fk_mainsequence_crm__transfer_job_workspace_uid_source_connecti",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_uid"],
            ["mainsequence_crm__workspace.uid"],
            name="fk_mainsequence_crm__transfer_job_workspace_uid",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("uid"),
        sa.UniqueConstraint(
            "workspace_uid", "uid", name="uq_mainsequence_crm__transfer_job_workspace_uid_uid"
        ),
    )
    op.create_index(
        "ix_mainsequence_crm__transfer_job_1",
        "mainsequence_crm__transfer_job",
        ["workspace_uid", "status", "created_at", "uid"],
        unique=False,
    )
    op.create_table(
        "mainsequence_crm__contact_tag",
        sa.Column("uid", sa.Uuid(), nullable=False),
        sa.Column("workspace_uid", sa.Uuid(), nullable=False),
        sa.Column("contact_uid", sa.Uuid(), nullable=False),
        sa.Column("tag_uid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_uid", "contact_uid"],
            ["mainsequence_crm__contact.workspace_uid", "mainsequence_crm__contact.uid"],
            name="fk_mainsequence_crm__contact_tag_workspace_uid_contact_uid",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_uid", "tag_uid"],
            ["mainsequence_crm__tag.workspace_uid", "mainsequence_crm__tag.uid"],
            name="fk_mainsequence_crm__contact_tag_workspace_uid_tag_uid",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_uid"],
            ["mainsequence_crm__workspace.uid"],
            name="fk_mainsequence_crm__contact_tag_workspace_uid",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("uid"),
        sa.UniqueConstraint(
            "workspace_uid",
            "contact_uid",
            "tag_uid",
            name="uq_mainsequence_crm__contact_tag_workspace_uid_contact_uid_tag_",
        ),
        sa.UniqueConstraint(
            "workspace_uid", "uid", name="uq_mainsequence_crm__contact_tag_workspace_uid_uid"
        ),
    )
    op.create_index(
        "ix_mainsequence_crm__contact_tag_1",
        "mainsequence_crm__contact_tag",
        ["workspace_uid", "tag_uid", "contact_uid"],
        unique=False,
    )
    op.create_table(
        "mainsequence_crm__deal",
        sa.Column("uid", sa.Uuid(), nullable=False),
        sa.Column("workspace_uid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_uid", sa.Uuid(), nullable=True),
        sa.Column("updated_by_uid", sa.Uuid(), nullable=True),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("owner_uid", sa.Uuid(), nullable=True),
        sa.Column("company_uid", sa.Uuid(), nullable=True),
        sa.Column("pipeline_uid", sa.Uuid(), nullable=False),
        sa.Column("stage_uid", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("category_key", sa.String(length=100), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("currency", sa.CHAR(length=3), nullable=False),
        sa.Column("expected_closing_date", sa.Date(), nullable=True),
        sa.Column("position", sa.BigInteger(), nullable=False),
        sa.Column("source_created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name="ck_mainsequence_crm__deal_3"),
        sa.CheckConstraint("amount IS NULL OR amount >= 0", name="ck_mainsequence_crm__deal_2"),
        sa.CheckConstraint("length(trim(name)) > 0", name="ck_mainsequence_crm__deal_1"),
        sa.CheckConstraint("position >= 0", name="ck_mainsequence_crm__deal_4"),
        sa.ForeignKeyConstraint(
            ["workspace_uid", "company_uid"],
            ["mainsequence_crm__company.workspace_uid", "mainsequence_crm__company.uid"],
            name="fk_mainsequence_crm__deal_workspace_uid_company_uid",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_uid", "pipeline_uid", "stage_uid"],
            [
                "mainsequence_crm__stage.workspace_uid",
                "mainsequence_crm__stage.pipeline_uid",
                "mainsequence_crm__stage.uid",
            ],
            name="fk_mainsequence_crm__deal_workspace_uid_pipeline_uid_stage_uid",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_uid", "pipeline_uid"],
            ["mainsequence_crm__pipeline.workspace_uid", "mainsequence_crm__pipeline.uid"],
            name="fk_mainsequence_crm__deal_workspace_uid_pipeline_uid",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_uid"],
            ["mainsequence_crm__workspace.uid"],
            name="fk_mainsequence_crm__deal_workspace_uid",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("uid"),
        sa.UniqueConstraint(
            "workspace_uid", "uid", name="uq_mainsequence_crm__deal_workspace_uid_uid"
        ),
    )
    op.create_index(
        "ix_mainsequence_crm__deal_1",
        "mainsequence_crm__deal",
        ["workspace_uid", "pipeline_uid", "stage_uid", "archived_at", "position", "uid"],
        unique=False,
    )
    op.create_index(
        "ix_mainsequence_crm__deal_2",
        "mainsequence_crm__deal",
        ["workspace_uid", "company_uid"],
        unique=False,
    )
    op.create_index(
        "ix_mainsequence_crm__deal_3",
        "mainsequence_crm__deal",
        ["workspace_uid", "owner_uid", "expected_closing_date"],
        unique=False,
    )
    op.create_table(
        "mainsequence_crm__task",
        sa.Column("uid", sa.Uuid(), nullable=False),
        sa.Column("workspace_uid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_uid", sa.Uuid(), nullable=True),
        sa.Column("updated_by_uid", sa.Uuid(), nullable=True),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("contact_uid", sa.Uuid(), nullable=False),
        sa.Column("owner_uid", sa.Uuid(), nullable=True),
        sa.Column("type_key", sa.String(length=100), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_by_uid", sa.Uuid(), nullable=True),
        sa.Column("source_created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("length(trim(text)) > 0", name="ck_mainsequence_crm__task_1"),
        sa.ForeignKeyConstraint(
            ["workspace_uid", "contact_uid"],
            ["mainsequence_crm__contact.workspace_uid", "mainsequence_crm__contact.uid"],
            name="fk_mainsequence_crm__task_workspace_uid_contact_uid",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_uid"],
            ["mainsequence_crm__workspace.uid"],
            name="fk_mainsequence_crm__task_workspace_uid",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("uid"),
        sa.UniqueConstraint(
            "workspace_uid", "uid", name="uq_mainsequence_crm__task_workspace_uid_uid"
        ),
    )
    op.create_index(
        "ix_mainsequence_crm__task_1",
        "mainsequence_crm__task",
        ["workspace_uid", "contact_uid"],
        unique=False,
    )
    op.create_index(
        "ix_mainsequence_crm__task_open_due",
        "mainsequence_crm__task",
        ["workspace_uid", "owner_uid", "due_at", "uid"],
        unique=False,
        postgresql_where=sa.text("completed_at IS NULL AND archived_at IS NULL"),
    )
    op.create_table(
        "mainsequence_crm__transfer_row",
        sa.Column("uid", sa.Uuid(), nullable=False),
        sa.Column("workspace_uid", sa.Uuid(), nullable=False),
        sa.Column("job_uid", sa.Uuid(), nullable=False),
        sa.Column("entity_type", sa.String(length=30), nullable=False),
        sa.Column("ordinal", sa.BigInteger(), nullable=False),
        sa.Column("external_id", sa.Text(), nullable=True),
        sa.Column("raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("raw_hash", sa.CHAR(length=64), nullable=False),
        sa.Column("normalized_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("normalized_hash", sa.CHAR(length=64), nullable=True),
        sa.Column("target_uid", sa.Uuid(), nullable=True),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("decision", sa.String(length=20), nullable=True),
        sa.Column("errors", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("warnings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("committed_command_uid", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "state IN ('staged','valid','blocked','committed','skipped','failed')",
            name="ck_mainsequence_crm__transfer_row_2",
        ),
        sa.CheckConstraint("ordinal >= 0", name="ck_mainsequence_crm__transfer_row_1"),
        sa.ForeignKeyConstraint(
            ["workspace_uid", "job_uid"],
            ["mainsequence_crm__transfer_job.workspace_uid", "mainsequence_crm__transfer_job.uid"],
            name="fk_mainsequence_crm__transfer_row_workspace_uid_job_uid",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_uid"],
            ["mainsequence_crm__workspace.uid"],
            name="fk_mainsequence_crm__transfer_row_workspace_uid",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("uid"),
        sa.UniqueConstraint(
            "workspace_uid",
            "job_uid",
            "entity_type",
            "ordinal",
            name="uq_mainsequence_crm__transfer_row_workspace_uid_job_uid_entity_",
        ),
        sa.UniqueConstraint(
            "workspace_uid", "uid", name="uq_mainsequence_crm__transfer_row_workspace_uid_uid"
        ),
    )
    op.create_index(
        "ix_mainsequence_crm__transfer_row_1",
        "mainsequence_crm__transfer_row",
        ["workspace_uid", "job_uid", "state", "ordinal", "uid"],
        unique=False,
    )
    op.create_table(
        "mainsequence_crm__deal_contact",
        sa.Column("uid", sa.Uuid(), nullable=False),
        sa.Column("workspace_uid", sa.Uuid(), nullable=False),
        sa.Column("deal_uid", sa.Uuid(), nullable=False),
        sa.Column("contact_uid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_uid", "contact_uid"],
            ["mainsequence_crm__contact.workspace_uid", "mainsequence_crm__contact.uid"],
            name="fk_mainsequence_crm__deal_contact_workspace_uid_contact_uid",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_uid", "deal_uid"],
            ["mainsequence_crm__deal.workspace_uid", "mainsequence_crm__deal.uid"],
            name="fk_mainsequence_crm__deal_contact_workspace_uid_deal_uid",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_uid"],
            ["mainsequence_crm__workspace.uid"],
            name="fk_mainsequence_crm__deal_contact_workspace_uid",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("uid"),
        sa.UniqueConstraint(
            "workspace_uid",
            "deal_uid",
            "contact_uid",
            name="uq_mainsequence_crm__deal_contact_workspace_uid_deal_uid_contac",
        ),
        sa.UniqueConstraint(
            "workspace_uid", "uid", name="uq_mainsequence_crm__deal_contact_workspace_uid_uid"
        ),
    )
    op.create_index(
        "ix_mainsequence_crm__deal_contact_1",
        "mainsequence_crm__deal_contact",
        ["workspace_uid", "contact_uid", "deal_uid"],
        unique=False,
    )
    op.create_table(
        "mainsequence_crm__note",
        sa.Column("uid", sa.Uuid(), nullable=False),
        sa.Column("workspace_uid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_uid", sa.Uuid(), nullable=True),
        sa.Column("updated_by_uid", sa.Uuid(), nullable=True),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("contact_uid", sa.Uuid(), nullable=True),
        sa.Column("deal_uid", sa.Uuid(), nullable=True),
        sa.Column("author_uid", sa.Uuid(), nullable=True),
        sa.Column("source_author_label", sa.String(length=255), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status_key", sa.String(length=100), nullable=True),
        sa.Column("legacy_type", sa.String(length=100), nullable=True),
        sa.Column("attachment_refs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.CheckConstraint(
            "jsonb_typeof(attachment_refs) = 'array'", name="ck_mainsequence_crm__note_3"
        ),
        sa.CheckConstraint(
            "(contact_uid IS NULL) <> (deal_uid IS NULL)", name="ck_mainsequence_crm__note_1"
        ),
        sa.CheckConstraint("length(trim(text)) > 0", name="ck_mainsequence_crm__note_2"),
        sa.ForeignKeyConstraint(
            ["workspace_uid", "contact_uid"],
            ["mainsequence_crm__contact.workspace_uid", "mainsequence_crm__contact.uid"],
            name="fk_mainsequence_crm__note_workspace_uid_contact_uid",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_uid", "deal_uid"],
            ["mainsequence_crm__deal.workspace_uid", "mainsequence_crm__deal.uid"],
            name="fk_mainsequence_crm__note_workspace_uid_deal_uid",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_uid"],
            ["mainsequence_crm__workspace.uid"],
            name="fk_mainsequence_crm__note_workspace_uid",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("uid"),
        sa.UniqueConstraint(
            "workspace_uid", "uid", name="uq_mainsequence_crm__note_workspace_uid_uid"
        ),
    )
    op.create_index(
        "ix_mainsequence_crm__note_1",
        "mainsequence_crm__note",
        ["workspace_uid", "contact_uid", "occurred_at", "uid"],
        unique=False,
    )
    op.create_index(
        "ix_mainsequence_crm__note_2",
        "mainsequence_crm__note",
        ["workspace_uid", "deal_uid", "occurred_at", "uid"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_mainsequence_crm__note_2", table_name="mainsequence_crm__note")
    op.drop_index("ix_mainsequence_crm__note_1", table_name="mainsequence_crm__note")
    op.drop_table("mainsequence_crm__note")
    op.drop_index(
        "ix_mainsequence_crm__deal_contact_1", table_name="mainsequence_crm__deal_contact"
    )
    op.drop_table("mainsequence_crm__deal_contact")
    op.drop_index(
        "ix_mainsequence_crm__transfer_row_1", table_name="mainsequence_crm__transfer_row"
    )
    op.drop_table("mainsequence_crm__transfer_row")
    op.drop_index(
        "ix_mainsequence_crm__task_open_due",
        table_name="mainsequence_crm__task",
        postgresql_where=sa.text("completed_at IS NULL AND archived_at IS NULL"),
    )
    op.drop_index("ix_mainsequence_crm__task_1", table_name="mainsequence_crm__task")
    op.drop_table("mainsequence_crm__task")
    op.drop_index("ix_mainsequence_crm__deal_3", table_name="mainsequence_crm__deal")
    op.drop_index("ix_mainsequence_crm__deal_2", table_name="mainsequence_crm__deal")
    op.drop_index("ix_mainsequence_crm__deal_1", table_name="mainsequence_crm__deal")
    op.drop_table("mainsequence_crm__deal")
    op.drop_index("ix_mainsequence_crm__contact_tag_1", table_name="mainsequence_crm__contact_tag")
    op.drop_table("mainsequence_crm__contact_tag")
    op.drop_index(
        "ix_mainsequence_crm__transfer_job_1", table_name="mainsequence_crm__transfer_job"
    )
    op.drop_table("mainsequence_crm__transfer_job")
    op.drop_index("ix_mainsequence_crm__stage_1", table_name="mainsequence_crm__stage")
    op.drop_table("mainsequence_crm__stage")
    op.drop_index(
        "ix_mainsequence_crm__source_identity_1", table_name="mainsequence_crm__source_identity"
    )
    op.drop_table("mainsequence_crm__source_identity")
    op.drop_index("ix_mainsequence_crm__contact_3", table_name="mainsequence_crm__contact")
    op.drop_index("ix_mainsequence_crm__contact_2", table_name="mainsequence_crm__contact")
    op.drop_index("ix_mainsequence_crm__contact_1", table_name="mainsequence_crm__contact")
    op.drop_table("mainsequence_crm__contact")
    op.drop_table("mainsequence_crm__tag")
    op.drop_table("mainsequence_crm__source_connection")
    op.drop_index(
        "ix_mainsequence_crm__pipeline_default",
        table_name="mainsequence_crm__pipeline",
        postgresql_where=sa.text("is_default = true"),
    )
    op.drop_table("mainsequence_crm__pipeline")
    op.drop_index(
        "ix_mainsequence_crm__entity_redirect_1", table_name="mainsequence_crm__entity_redirect"
    )
    op.drop_table("mainsequence_crm__entity_redirect")
    op.drop_index("ix_mainsequence_crm__company_3", table_name="mainsequence_crm__company")
    op.drop_index("ix_mainsequence_crm__company_2", table_name="mainsequence_crm__company")
    op.drop_index("ix_mainsequence_crm__company_1", table_name="mainsequence_crm__company")
    op.drop_table("mainsequence_crm__company")
    op.drop_index(
        "ix_mainsequence_crm__command_receipt_1", table_name="mainsequence_crm__command_receipt"
    )
    op.drop_table("mainsequence_crm__command_receipt")
    op.drop_index(
        "ix_mainsequence_crm__activity_event_2", table_name="mainsequence_crm__activity_event"
    )
    op.drop_index(
        "ix_mainsequence_crm__activity_event_1", table_name="mainsequence_crm__activity_event"
    )
    op.drop_table("mainsequence_crm__activity_event")
    op.drop_table("mainsequence_crm__workspace")
    # ### end Alembic commands ###
