"""add contact company affiliations

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-23 19:15:03.095171

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: Union[str, Sequence[str], None] = "0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mainsequence_crm__contact_company_affiliation",
        sa.Column("uid", sa.Uuid(), nullable=False),
        sa.Column("workspace_uid", sa.Uuid(), nullable=False),
        sa.Column("contact_uid", sa.Uuid(), nullable=False),
        sa.Column("company_uid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by_uid", sa.Uuid(), nullable=True),
        sa.Column("updated_by_uid", sa.Uuid(), nullable=True),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("started_period", sa.String(length=10), nullable=True),
        sa.Column("ended_period", sa.String(length=10), nullable=True),
        sa.Column("job_title", sa.String(length=255), nullable=True),
        sa.CheckConstraint(
            "NOT is_primary OR (status='current' AND archived_at IS NULL)",
            name="ck_mainsequence_crm__affiliation_primary",
        ),
        sa.CheckConstraint(
            "ended_period IS NULL OR ended_period ~ '^[0-9]{4}(-[0-9]{2}(-[0-9]{2})?)?$'",
            name="ck_mainsequence_crm__affiliation_end_shape",
        ),
        sa.CheckConstraint(
            "ended_period IS NULL OR status='former'",
            name="ck_mainsequence_crm__affiliation_end_status",
        ),
        sa.CheckConstraint(
            "started_period IS NULL OR started_period ~ '^[0-9]{4}(-[0-9]{2}(-[0-9]{2})?)?$'",
            name="ck_mainsequence_crm__affiliation_start_shape",
        ),
        sa.CheckConstraint(
            "status IN ('current','former','unknown')",
            name="ck_mainsequence_crm__affiliation_status",
        ),
        sa.CheckConstraint("version > 0", name="ck_mainsequence_crm__affiliation_version"),
        sa.ForeignKeyConstraint(
            ["workspace_uid", "company_uid"],
            ["mainsequence_crm__company.workspace_uid", "mainsequence_crm__company.uid"],
            name="fk_mainsequence_crm__affiliation_company",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_uid", "contact_uid"],
            ["mainsequence_crm__contact.workspace_uid", "mainsequence_crm__contact.uid"],
            name="fk_mainsequence_crm__affiliation_contact",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_uid"],
            ["mainsequence_crm__workspace.uid"],
            name="fk_mainsequence_crm__affiliation_workspace",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("uid"),
        sa.UniqueConstraint(
            "workspace_uid", "uid", name="uq_mainsequence_crm__affiliation_workspace_uid_uid"
        ),
    )
    op.create_index(
        "ix_mainsequence_crm__affiliation_company_status",
        "mainsequence_crm__contact_company_affiliation",
        ["workspace_uid", "company_uid", "status", "contact_uid"],
        unique=False,
    )
    op.create_index(
        "ix_mainsequence_crm__affiliation_contact_timeline",
        "mainsequence_crm__contact_company_affiliation",
        ["workspace_uid", "contact_uid", "started_period", "uid"],
        unique=False,
    )
    op.create_index(
        "uq_mainsequence_crm__affiliation_primary_current",
        "mainsequence_crm__contact_company_affiliation",
        ["workspace_uid", "contact_uid"],
        unique=True,
        postgresql_where=sa.text("is_primary AND archived_at IS NULL"),
    )
    # ### end Alembic commands ###
    # The legacy company UID denotes a current primary association, but says
    # nothing about when employment started or ended. Preserve that distinction.
    op.execute(
        sa.text("""
        INSERT INTO mainsequence_crm__contact_company_affiliation
            (uid, workspace_uid, contact_uid, company_uid, created_at, updated_at,
             created_by_uid, updated_by_uid, version, archived_at, status,
             is_primary, started_period, ended_period, job_title)
        SELECT md5(c.uid::text || '-initial-company-affiliation')::uuid,
               c.workspace_uid, c.uid, c.company_uid, NOW(), NOW(),
               c.created_by_uid, c.updated_by_uid, 1, NULL, 'current',
               TRUE, NULL, NULL, NULL
        FROM mainsequence_crm__contact AS c
        WHERE c.company_uid IS NOT NULL
    """)
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_mainsequence_crm__affiliation_primary_current",
        table_name="mainsequence_crm__contact_company_affiliation",
        postgresql_where=sa.text("is_primary AND archived_at IS NULL"),
    )
    op.drop_index(
        "ix_mainsequence_crm__affiliation_contact_timeline",
        table_name="mainsequence_crm__contact_company_affiliation",
    )
    op.drop_index(
        "ix_mainsequence_crm__affiliation_company_status",
        table_name="mainsequence_crm__contact_company_affiliation",
    )
    op.drop_table("mainsequence_crm__contact_company_affiliation")
    # ### end Alembic commands ###
