"""add interactions and solution selling

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-24 14:40:09.025971

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0006'
down_revision: Union[str, Sequence[str], None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_mainsequence_crm__deal_uid_company_uid', 'mainsequence_crm__deal', ['uid', 'company_uid'])
    op.create_table('mainsequence_crm__solution_selling_prompter',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_uid', sa.Uuid(), nullable=True),
    sa.Column('updated_by_uid', sa.Uuid(), nullable=True),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('length(template) > 0'),
    sa.CheckConstraint('length(trim(name)) > 0'),
    sa.CheckConstraint('version > 0'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index('ix_mainsequence_crm__ss_prompter_kind', 'mainsequence_crm__solution_selling_prompter', ['kind'], unique=False)
    op.create_table('mainsequence_crm__solution_selling_prospecting_profile',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('market_context', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('potential_pain', sa.Text(), nullable=False),
    sa.Column('likely_reasons', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('likely_impacts', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('research_guidance', sa.Text(), nullable=True),
    sa.Column('opening_message', sa.Text(), nullable=True),
    sa.Column('suggested_next_commitment', sa.Text(), nullable=True),
    sa.Column('diagnosis_template', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_uid', sa.Uuid(), nullable=True),
    sa.Column('updated_by_uid', sa.Uuid(), nullable=True),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("diagnosis_template IS NULL OR jsonb_typeof(diagnosis_template) = 'object'"),
    sa.CheckConstraint("jsonb_typeof(likely_impacts) = 'array'"),
    sa.CheckConstraint("jsonb_typeof(likely_reasons) = 'array'"),
    sa.CheckConstraint('length(trim(name)) > 0'),
    sa.CheckConstraint('version > 0'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index('ix_mainsequence_crm__ss_profile_context', 'mainsequence_crm__solution_selling_prospecting_profile', ['market_context', 'role'], unique=False)
    op.create_table('mainsequence_crm__interaction',
    sa.Column('company_uid', sa.Uuid(), nullable=False),
    sa.Column('contact_uid', sa.Uuid(), nullable=True),
    sa.Column('deal_uid', sa.Uuid(), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('research_notes', sa.Text(), nullable=True),
    sa.Column('discussion_plan', sa.Text(), nullable=True),
    sa.Column('outcome_notes', sa.Text(), nullable=True),
    sa.Column('next_steps', sa.Text(), nullable=True),
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_uid', sa.Uuid(), nullable=True),
    sa.Column('updated_by_uid', sa.Uuid(), nullable=True),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("kind IN ('call','meeting','workshop','email')"),
    sa.CheckConstraint("status IN ('planned','completed','cancelled')"),
    sa.CheckConstraint('length(trim(subject)) > 0'),
    sa.CheckConstraint('version > 0'),
    sa.ForeignKeyConstraint(['company_uid'], ['mainsequence_crm__company.uid'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['contact_uid'], ['mainsequence_crm__contact.uid'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deal_uid', 'company_uid'], ['mainsequence_crm__deal.uid', 'mainsequence_crm__deal.company_uid'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index('ix_mainsequence_crm__interaction_company', 'mainsequence_crm__interaction', ['company_uid', 'scheduled_at'], unique=False)
    op.create_index('ix_mainsequence_crm__interaction_contact', 'mainsequence_crm__interaction', ['contact_uid'], unique=False)
    op.create_index('ix_mainsequence_crm__interaction_deal', 'mainsequence_crm__interaction', ['deal_uid'], unique=False)
    op.create_table('mainsequence_crm__solution_selling',
    sa.Column('deal_uid', sa.Uuid(), nullable=False),
    sa.Column('company_uid', sa.Uuid(), nullable=False),
    sa.Column('pain_summary', sa.Text(), nullable=True),
    sa.Column('pain_contact_uid', sa.Uuid(), nullable=True),
    sa.Column('power_summary', sa.Text(), nullable=True),
    sa.Column('power_contact_uid', sa.Uuid(), nullable=True),
    sa.Column('sponsor_contact_uid', sa.Uuid(), nullable=True),
    sa.Column('vision_summary', sa.Text(), nullable=True),
    sa.Column('value_summary', sa.Text(), nullable=True),
    sa.Column('control_summary', sa.Text(), nullable=True),
    sa.Column('key_players', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('pain_chain', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('evaluation_plan', sa.Text(), nullable=True),
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_uid', sa.Uuid(), nullable=True),
    sa.Column('updated_by_uid', sa.Uuid(), nullable=True),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("jsonb_typeof(key_players) = 'array'"),
    sa.CheckConstraint("jsonb_typeof(pain_chain) = 'array'"),
    sa.CheckConstraint('version > 0'),
    sa.ForeignKeyConstraint(['company_uid'], ['mainsequence_crm__company.uid'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['deal_uid', 'company_uid'], ['mainsequence_crm__deal.uid', 'mainsequence_crm__deal.company_uid'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pain_contact_uid'], ['mainsequence_crm__contact.uid'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['power_contact_uid'], ['mainsequence_crm__contact.uid'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sponsor_contact_uid'], ['mainsequence_crm__contact.uid'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('deal_uid')
    )
    op.create_index('ix_mainsequence_crm__solution_selling_company', 'mainsequence_crm__solution_selling', ['company_uid'], unique=False)
    op.create_table('mainsequence_crm__solution_selling_lead',
    sa.Column('contact_uid', sa.Uuid(), nullable=False),
    sa.Column('profile_uid', sa.Uuid(), nullable=True),
    sa.Column('owner_uid', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('next_task_uid', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_uid', sa.Uuid(), nullable=True),
    sa.Column('updated_by_uid', sa.Uuid(), nullable=True),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('to_contact','contacted','qualified','nurture','disqualified')"),
    sa.CheckConstraint('version > 0'),
    sa.ForeignKeyConstraint(['contact_uid'], ['mainsequence_crm__contact.uid'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['next_task_uid'], ['mainsequence_crm__task.uid'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['profile_uid'], ['mainsequence_crm__solution_selling_prospecting_profile.uid'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('contact_uid')
    )
    op.create_index('ix_mainsequence_crm__ss_lead_status', 'mainsequence_crm__solution_selling_lead', ['status', 'owner_uid'], unique=False)
    op.create_table('mainsequence_crm__solution_selling_diagnosis',
    sa.Column('interaction_uid', sa.Uuid(), nullable=False),
    sa.Column('contact_uid', sa.Uuid(), nullable=False),
    sa.Column('solution_selling_uid', sa.Uuid(), nullable=True),
    sa.Column('business_issue', sa.Text(), nullable=False),
    sa.Column('matrix', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('conclusion', sa.Text(), nullable=True),
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_uid', sa.Uuid(), nullable=True),
    sa.Column('updated_by_uid', sa.Uuid(), nullable=True),
    sa.Column('version', sa.BigInteger(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("jsonb_typeof(matrix) = 'object'"),
    sa.CheckConstraint('length(trim(business_issue)) > 0'),
    sa.CheckConstraint('version > 0'),
    sa.ForeignKeyConstraint(['contact_uid'], ['mainsequence_crm__contact.uid'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['interaction_uid'], ['mainsequence_crm__interaction.uid'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['solution_selling_uid'], ['mainsequence_crm__solution_selling.uid'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index('ix_mainsequence_crm__ss_diagnosis_assessment', 'mainsequence_crm__solution_selling_diagnosis', ['solution_selling_uid'], unique=False)
    op.create_index('ix_mainsequence_crm__ss_diagnosis_interaction', 'mainsequence_crm__solution_selling_diagnosis', ['interaction_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mainsequence_crm__ss_diagnosis_interaction', table_name='mainsequence_crm__solution_selling_diagnosis')
    op.drop_index('ix_mainsequence_crm__ss_diagnosis_assessment', table_name='mainsequence_crm__solution_selling_diagnosis')
    op.drop_table('mainsequence_crm__solution_selling_diagnosis')
    op.drop_index('ix_mainsequence_crm__ss_lead_status', table_name='mainsequence_crm__solution_selling_lead')
    op.drop_table('mainsequence_crm__solution_selling_lead')
    op.drop_index('ix_mainsequence_crm__solution_selling_company', table_name='mainsequence_crm__solution_selling')
    op.drop_table('mainsequence_crm__solution_selling')
    op.drop_index('ix_mainsequence_crm__interaction_deal', table_name='mainsequence_crm__interaction')
    op.drop_index('ix_mainsequence_crm__interaction_contact', table_name='mainsequence_crm__interaction')
    op.drop_index('ix_mainsequence_crm__interaction_company', table_name='mainsequence_crm__interaction')
    op.drop_table('mainsequence_crm__interaction')
    op.drop_constraint('uq_mainsequence_crm__deal_uid_company_uid', 'mainsequence_crm__deal', type_='unique')
    op.drop_index('ix_mainsequence_crm__ss_profile_context', table_name='mainsequence_crm__solution_selling_prospecting_profile')
    op.drop_table('mainsequence_crm__solution_selling_prospecting_profile')
    op.drop_index('ix_mainsequence_crm__ss_prompter_kind', table_name='mainsequence_crm__solution_selling_prompter')
    op.drop_table('mainsequence_crm__solution_selling_prompter')
    # ### end Alembic commands ###
